Update maven.yml

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -27,11 +27,14 @@ jobs:
         java-version: '8'
         distribution: 'temurin'
         cache: maven
-    - name: List
-      run: ls
     - name: Build with Maven
+      run: ./mvnw compile
+    - name: Test with Maven
       run: ./mvnw test
-
-    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
-    - name: Update dependency graph
-      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Java Tests            # Name of the check run which will be created
+        path: target/surefire-reports/*.xml    # Path to test results
+        reporter: java-junit        # Format of test results
